import fs from 'fs';
import { createClient } from "@supabase/supabase-js";

// Safe Unsplash car images that will definitely load
const safeImages = [
  "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
  "https://images.unsplash.com/photo-1503376712341-ea78a4879201?w=800&q=80",
  "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?w=800&q=80",
  "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
  "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80",
  "https://images.unsplash.com/photo-1502877338535-34b1611c0f18?w=800&q=80",
  "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80",
  "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80",
  "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&q=80",
  "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80"
];

const categories = ["SUV", "Sedan", "Coupe", "Convertible", "Truck", "Hatchback", "Luxury"];
const makes = ["BMW", "Mercedes-Benz", "Audi", "Ferrari", "Porsche", "Lamborghini", "Ford", "Toyota", "Chevrolet", "Rolls Royce"];

const supabase = createClient(
  "https://yehnqmufskriwtogpwzt.supabase.co", 
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaG5xbXVmc2tyaXd0b2dwd3p0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjE0OTc4MiwiZXhwIjoyMTAxNzI1NzgyfQ.VvlCRLsTua27p8FSvS1HnH5DGn-cCtlbFrDbU_5VgO8"
);

async function run() {
  console.log("Fetching existing vehicles to build the SQL...");
  const { data: vehicles } = await supabase.from('vehicles').select('*').limit(40);
  
  if (!vehicles || vehicles.length === 0) {
    console.error("No vehicles found in db!");
    return;
  }

  let sql = `-- Seed file generated by migration script\n`;
  sql += `-- Instructions: Copy and paste this into your Supabase SQL Editor to insert vehicles.\n\n`;

  vehicles.forEach((v, index) => {
    // Assign a safe working image so it loads
    const imgUrl = safeImages[index % safeImages.length];
    
    // Assign a category to body_type if it doesn't have one
    const category = v.body_type && v.body_type !== '' ? v.body_type : categories[Math.floor(Math.random() * categories.length)];
    
    const make = v.make && v.make !== 'Unknown' ? v.make : makes[Math.floor(Math.random() * makes.length)];
    const year = v.year || (2015 + Math.floor(Math.random() * 10));

    // Escape single quotes for SQL
    const name = v.name.replace(/'/g, "''");
    const slug = v.slug.replace(/'/g, "''");
    const desc = v.description.replace(/'/g, "''").substring(0, 800); // limit length for sql file
    
    sql += `INSERT INTO public.vehicles (slug, name, description, price, make, year, body_type, images, is_sold, created_at)\n`;
    sql += `VALUES (\n`;
    sql += `  '${slug}',\n`;
    sql += `  '${name}',\n`;
    sql += `  '${desc}',\n`;
    sql += `  ${v.price},\n`;
    sql += `  '${make}',\n`;
    sql += `  ${year},\n`;
    sql += `  '${category}',\n`;
    sql += `  ARRAY['${imgUrl}']::text[],\n`;
    sql += `  false,\n`;
    sql += `  '${v.created_at}'\n`;
    sql += `) ON CONFLICT (slug) DO UPDATE SET \n`;
    sql += `  name = EXCLUDED.name,\n`;
    sql += `  description = EXCLUDED.description,\n`;
    sql += `  price = EXCLUDED.price,\n`;
    sql += `  make = EXCLUDED.make,\n`;
    sql += `  year = EXCLUDED.year,\n`;
    sql += `  body_type = EXCLUDED.body_type,\n`;
    sql += `  images = EXCLUDED.images,\n`;
    sql += `  is_sold = EXCLUDED.is_sold,\n`;
    sql += `  created_at = EXCLUDED.created_at;\n\n`;
  });

  const artifactPath = '/home/philding/Desktop/apps/codified-car-site/supabase/migrations/20260808124000_seed_vehicles.sql';
  fs.writeFileSync(artifactPath, sql, 'utf8');
  console.log(`Generated SQL at ${artifactPath}`);
}

run().catch(console.error);
